export const conversationStarters = [
  {id: 1, texto: "¿Qué te trae a Ravenhollow, forastero?"},
  {id: 8, texto: "Los bosques están llenos de peligros, ¿estás seguro de que quieres adentrarte en ellos?"},
  {id: 15, texto: "Algo no anda bien en esta aldea, ¿no lo sientes?"},
  {id: 22, texto: "No todos en esta aldea son lo que parecen, forastero..."},
  {id: 29, texto: "¿No crees que nos hemos encontrado antes en circunstancias diferentes?"},
  {id: 36, texto: "Sabes, el último héroe que pasó por aquí fue engañado por alguien en esta aldea..."},
  {id: 45, texto: "¿Has estado recolectando objetos de los monstruos que aparecen en los bosques cercanos?"},
  {id: 52, texto: "¡Eh, tú! ¿Eres uno de esos cazadores de monstruos, verdad?"},
  {id: 61, texto: "Hace muchos años, un misterioso viajero llegó a nuestra aldea con la intención de liberarla del mal que la acechaba. Pero su intento fue en vano, y acabó encontrando una trágica muerte."},
];

export const conversationOptions = [
  {id: 1,texto:"¿Qué te trae a Ravenhollow, forastero?",
    opciones: [
      { texto: "Vengo a ayudar a la aldea.", siguienteId: 2 },
      { texto: "Sólo estoy de paso.", siguienteId: 3 },
    ],
  },
  {id: 2,texto:"Muchos han venido con la misma intención y han fracasado. ¿Por qué deberíamos confiar en ti?",
    opciones: [
      { texto: "Soy diferente. Confía en mí y lo demostraré.", siguienteId: 4 },
      {
        texto: "Entiendo vuestra desconfianza, pero quiero ayudar.",
        siguienteId: 5,
      },
    ],
  },
  {id: 3,texto:"No te confíes. Los secretos de esta aldea pueden ser peligrosos incluso para los que sólo están de paso.",
    opciones: [
      { texto: "Gracias por la advertencia, tendré cuidado.", siguienteId: 6 },
      { texto: "No me asustan los secretos.", siguienteId: 7 },
    ],
  },
  {id: 4,texto: "Eso espero. Procura no meterte en problemas.",
    final: true,
  },
  {id: 5,texto:"Bueno, puede que nos hayas convencido. Pero no te equivoques, te estaremos observando.",
    final: true,
  },
  {id: 6,texto:"Eres sabio. No te preocupes, si necesitas algo, no dudes en preguntar.",
    final: true,
  },
  {id: 7,texto:"La valentía puede ser tu perdición. Ten cuidado con lo que desentierres.",
    final: true,
  },
  {id: 8,texto:"Los bosques están llenos de peligros, ¿estás seguro de que quieres adentrarte en ellos?",
    opciones: [
      { texto: "Sí, no temo a los peligros.", siguienteId: 9 },
      { texto: "Tal vez tengas razón, quizás no deba ir.", siguienteId: 10 },
    ],
  },
  {id: 9,texto:"Admirable, pero recuerda que la oscuridad acecha en cada rincón. ¿Estás preparado para enfrentarte a ella?",
    opciones: [
      {texto: "Sí, estoy listo para enfrentarme a cualquier desafío.",
        siguienteId: 11,
      },
      {texto:"Quizá necesite más preparación antes de adentrarme en los bosques.",
        siguienteId: 12,
      },
    ],
  },
  {id: 10,texto:"Es mejor ser prudente. Si cambias de opinión, asegúrate de estar bien preparado.",
    opciones: [
      {texto: "Gracias por el consejo, lo tendré en cuenta.",
        siguienteId: 13,
      },
      {texto: "Entiendo, estaré alerta en todo momento.", 
      siguienteId: 14 },
    ],
  },
  {id: 11,texto:"Buena suerte, valiente forastero. Esperamos que puedas enfrentarte a los horrores que esconde el bosque.",
    final: true,
  },
  {id: 12,texto:"La cautela es una virtud en estos tiempos oscuros. Regresa cuando te sientas listo.",
    final: true,
  },
  {id: 13,texto: "Eso es lo más sensato. Que la fortuna te acompañe en tus andanzas.",
    final: true,
  },
  {id: 14,texto: "La vigilancia es clave en estos parajes. Cuídate, forastero.",
    final: true,
  },
  {id: 15,texto: "Algo no anda bien en esta aldea, ¿no lo sientes?",
    opciones: [
      {texto: "Sí, puedo sentir la oscuridad que se cierne sobre este lugar.",
        siguienteId: 16,
      },
      {texto: "No estoy seguro de lo que dices. Parece una aldea normal.",
        siguienteId: 17,
      },
    ],
  },
  {id: 16,texto:"La oscuridad ha dejado su marca aquí. ¿Crees que puedes descubrir qué ha ocurrido?",
    opciones: [
      {texto:"Haré todo lo posible por descubrir la verdad y ayudar a la aldea.",
        siguienteId: 18,
      },
      {texto: "No prometo nada, pero intentaré averiguarlo.",
        siguienteId: 19,
      },
    ],
  },
  {id: 17,texto:"No te dejes engañar por las apariencias, forastero. La aldea guarda secretos que pueden destruir a los desprevenidos.",
    opciones: [
      { texto: "Gracias por la advertencia, estaré alerta.", siguienteId: 20 },
      { texto: "No creo en cuentos, me mantendré escéptico.", siguienteId: 21 },
    ],
  },
  {id: 18,texto:"Te agradecemos tu valentía. Ojalá puedas liberarnos de esta sombra que nos atormenta.",
    final: true,
  },
  {id: 19,texto:"A veces, eso es lo único que se puede hacer. Buena suerte en tu búsqueda, forastero.",
    final: true,
  },
  {id: 20,texto:"Esa es la actitud correcta. Mantén la mente abierta y no te dejes engañar por lo que ves.",
    final: true,
  },
  {id: 21,texto:"El escepticismo puede ser útil, pero no dejes que te ciegue ante la verdad. Ten cuidado.",
    final: true,
  },
  {id: 22,texto: "No todos en esta aldea son lo que parecen, forastero...",
    opciones: [
      { texto: "¿A qué te refieres?", siguienteId: 23 },
      { texto: "No entiendo lo que quieres decir.", siguienteId: 24 },
    ],
  },
  {id: 23,texto:"Hay rumores de que algunas personas no son realmente humanas. Dicen que se transforman en monstruos cuando cae la noche.",
    opciones: [
      {texto: "Eso suena aterrador. ¿Cómo puedo saber en quién confiar?",
        siguienteId: 25,
      },
      {texto: "Quizás sean sólo rumores infundados.", siguienteId: 26 },
    ],
  },
  {id: 24,texto:"Hay quienes murmuran que algunos aldeanos no son lo que parecen. Cambian de forma cuando las sombras los envuelven.",
    opciones: [
      {texto: "Es inquietante. ¿Hay alguna forma de saber quiénes son?",
        siguienteId: 27,
      },
      {texto: "No creo en historias de miedo.", siguienteId: 28 },
    ],
  },
  {id: 25,texto:"Es difícil de decir. Sólo te aconsejo que mantengas tus ojos y oídos abiertos. La verdad siempre sale a la luz.",
    final: true,
  },
  {id: 26,texto:"Tal vez tengas razón, pero nunca está de más ser cauteloso. No todo es lo que parece en Ravenhollow.",
    final: true,
  },
  {id: 27,texto:"Mantente alerta y observa atentamente. Las apariencias pueden engañar, pero las acciones revelan la verdadera naturaleza de alguien.",
    final: true,
  },
  {id: 28,texto:"Es comprensible, pero no subestimes los secretos que puede esconder esta aldea. La precaución nunca está de más.",
    final: true,
  },
  {id: 29,texto:"¿No crees que nos hemos encontrado antes en circunstancias diferentes?",
    opciones: [
      { texto: "No estoy seguro, ¿debería recordarte?", siguienteId: 30 },
      { texto: "No lo creo, pero quizás me equivoco.", siguienteId: 31 },
    ],
  },
  {id: 30,texto:"Bueno, solo tú puedes responder a esa pregunta. A veces, las personas entran y salen de nuestras vidas sin que nos demos cuenta.",
    opciones: [
      {texto: "Entonces, ¿estás sugiriendo que te conozco de algún lugar?",
        siguienteId: 32,
      },
      {texto: "Creo que te estás confundiendo con otra persona.",
        siguienteId: 33,
      },
    ],
  },
  {id: 31,texto:"Tal vez sí, tal vez no. Pero, ¿qué importa? A veces, el destino nos presenta oportunidades para que las aprovechemos.",
    opciones: [
      { texto: "Eres muy misterioso, pero me intriga.", siguienteId: 34 },
      { texto: "No me interesa jugar a tus juegos.", siguienteId: 35 },
    ],
  },
  {id: 32,texto:"Esa es una pregunta que solo tú puedes responder. Pero si te quedas el tiempo suficiente, quizás descubras la verdad.",
    final: true,
  },
  {id: 33,texto:"Quizás tengas razón, pero nunca está de más reflexionar sobre las personas que hemos conocido a lo largo de nuestras vidas.",
    final: true,
  },
  {id: 34,texto:"La vida está llena de misterios, y a veces, las respuestas se encuentran en los lugares más inesperados.",
    final: true,
  },
  {id: 35,texto:"Entiendo, pero no subestimes el poder del destino y las conexiones que creamos con los demás.",
    final: true,
  },
  {id: 36,texto:
      "Sabes, el último héroe que pasó por aquí fue engañado por alguien en esta aldea...",
    opciones: [
      {texto: "¿En serio? Cuéntame más sobre eso.", 
      siguienteId: 37 },
      {texto: "No me sorprende, este lugar parece lleno de secretos.",
        siguienteId: 38,
      },
    ],
  },
  {id: 37,texto:"Bueno, la verdad es que... ¿Has notado lo bonitas que están las flores esta temporada? Son realmente impresionantes.",
    opciones: [
      {texto: "No cambies de tema. ¿Qué le pasó al último héroe?",
        siguienteId: 39,
      },
      {texto:"Sí, las flores son hermosas, pero quiero saber más sobre el héroe engañado.",
        siguienteId: 40,
      },
    ],
  },
  {id: 38,texto:"Sí, es cierto... Pero, ¿has probado el pastel de manzana de la panadería? Es delicioso.",
    opciones: [
      {texto: "No me importa el pastel. Dime qué pasó con ese héroe.",
        siguienteId: 41,
      },
      {texto:"Quizás lo pruebe más tarde, pero primero quiero saber más sobre el héroe.",
        siguienteId: 42,
      },
    ],
  },
  {id: 39,texto:"Lo siento, pero no puedo hablar más de eso. Solo te diré que siempre es mejor asegurarse de en quién confías.",
    final: true,
  },
  {id: 40,texto:"Ah, entiendo tu curiosidad, pero no puedo decirte más. La lección aquí es no confiar en todo el mundo a ciegas.",
    final: true,
  },
  {id: 41,texto:"Lamento si te molestó mi comentario. La verdad es que no puedo contarte más. Solo te aconsejo que tengas cuidado.",
    final: true,
  },
  {id: 42,texto:"Aprecio tu interés, pero no puedo revelarte más detalles. Solo recuerda ser cauteloso y no confiar en todos.",
    final: true,
  },
  {id: 45,texto:"¿Has estado recolectando objetos de los monstruos que aparecen en los bosques cercanos?",
    opciones: [
      {texto: "Sí, he estado haciéndolo. ¿Por qué lo preguntas?",
        siguienteId: 46,
      },
      {texto: "No, no lo he estado haciendo. ¿Por qué es importante?",
        siguienteId: 47,
      },
    ],
  },
  {id: 46,texto:"Algunos de los objetos que los héroes han recuperado en el pasado me resultan muy familiares, como si hubieran pertenecido a alguien en la aldea.",
    opciones: [
      { texto: "¿Crees que los monstruos se los robaron?", siguienteId: 48 },
      {texto:"¿Qué quieres decir con eso? ¿Crees que algunos de los aldeanos son monstruos?",
        siguienteId: 49,
      },
    ],
  },
  {id: 47,texto:"Es posible que no tengas nada que ver con esto, pero he notado que algunos de los objetos recuperados por los héroes parecen haber pertenecido a alguien en la aldea.",
    opciones: [
      { texto: "¿Crees que los monstruos los robaron?", 
      siguienteId: 48 },
      {texto: "¿Estás insinuando que algunos de los aldeanos son monstruos?",
        siguienteId: 49,
      },
    ],
  },
  {id: 48,texto:"Eso es lo que la mayoría de la gente cree, pero no puedo evitar preguntarme si hay algo más detrás de todo esto...",
    opciones: [
      { texto: "¿Algo más? ¿A qué te refieres?", 
      siguienteId: 50 },
      {texto:"Espero que no haya nada más detrás de esto. Ya tengo suficientes problemas con los monstruos.",
        siguienteId: 51,
      },
    ],
  },
  {id: 49,texto:"¡Oh no, no, no! Por supuesto que no. Sólo es que algunos de los objetos que los héroes recuperan parecen familiares, eso es todo.",
    opciones: [
      {texto:"Está bien, supongo que no hay nada de qué preocuparse entonces.",
        siguienteId: 51,
      },
      {texto: "¿Puedo ver esos objetos? Tal vez pueda identificarlos.",
        siguienteId: 50,
      },
    ],
  },
  {id: 50,texto:"Bueno, si estás interesado, podría mostrarte algunos de ellos. Pero por favor, no digas nada a nadie más sobre esto. No quiero causar pánico en la aldea.",
    final: true,
  },
  {id: 51,texto:"Sí, los monstruos son un problema suficiente como para preocuparnos. Pero igual me parece extraño que algunos objetos parezcan pertenecer a la aldea...",
    final: true,
  },
  {id: 52,texto: "¡Eh, tú! ¿Eres uno de esos cazadores de monstruos, verdad?",
    opciones: [
      { texto: "Sí, lo soy. ¿Hay algún problema?", 
      siguienteId: 53 },
      { texto: "¿Por qué lo preguntas?", 
      siguienteId: 54 },
    ],
  },
  {id: 53,texto:"¡Cómo puedes hacer eso! ¿No te das cuenta de que estás matando a criaturas que tienen tanto derecho a vivir como nosotros?",
    opciones: [
      {texto:"Pero los monstruos atacan a los aldeanos. No tenemos otra opción.",
        siguienteId: 55,
      },
      {texto: "Tienes razón, no deberíamos matar a criaturas inocentes.",
        siguienteId: 56,
      },
    ],
  },
  {id: 54,texto:"No me gusta la idea de que andes matando a todas esas criaturas. ¿No te das cuenta de que tienen derecho a vivir también?",
    opciones: [
      {texto: "Bueno, si no los matamos, ellos nos matarán a nosotros.",
        siguienteId: 55,
      },
      {texto: "Tienes razón, no deberíamos matar a criaturas inocentes.",
        siguienteId: 56,
      },
    ],
  },
  {
    id: 55,
    texto:
      "Pero, ¿cómo puedes estar seguro de que son realmente monstruos? Tal vez sólo estén tratando de protegerse de nosotros, los verdaderos monstruos.",
    opciones: [
      { texto: "¿A qué te refieres?", siguienteId: 57 },
      {texto:"No creo que esos monstruos antes fuesen nada que merezca vivir.",
        siguienteId: 58,
      },
    ],
  },
  {id: 56,texto:"Me alegra que estemos de acuerdo. Hay que aprender a convivir con las criaturas del bosque, no matarlas.",
    final: true,
  },
  {id: 57,texto:"Bueno, ¿quién sabe? Tal vez algunos de los monstruos que matas antes eran ... otra cosa y cambiaron por la maldición del bosque.",
    opciones: [
      { texto: "¿Qué quieres decir con eso?", siguienteId: 59 },
      { texto: "No creo que eso sea posible.", siguienteId: 60 },
    ],
  },
  {id: 58,texto:"Quizás tengas razón, pero no estoy seguro. A veces siento vínculos con las criaturas que matamos y pienso que quizá fueron algo diferente en otro momento.",
    opciones: [
      { texto: "¿A qué te refieres?", siguienteId: 59 },
      { texto: "No creo que eso sea posible.", siguienteId: 60 },
    ],
  },
  {id: 59,texto:"No estoy seguro de lo que quiero decir. Tal vez simplemente deberíamos pensar antes de matar a cualquier criatura que se nos atraviese en el camino.",
    final: true,
  },
  {id: 60,texto:"Puede que tengas razón. De todas formas, siempre es mejor estar seguros antes de tomar una decisión que podría ser irreversible.",
    final: true,
  },

  {id: 61,texto:"Hace muchos años, un misterioso viajero llegó a nuestra aldea con la intención de liberarla del mal que la acechaba. Pero su intento fue en vano, y acabó encontrando una trágica muerte.",
    opciones: [
      { texto: "¿Cómo sucedió eso?", siguienteId: 62 },
      { texto: "¿Qué pasó después?", siguienteId: 63 },
    ],
  },
  {id: 62,texto:"Se dice que se internó en el bosque para enfrentarse a las criaturas que lo habitaban. Pero nunca regresó. Su cuerpo nunca fue encontrado, y su espada quedó abandonada en medio de la maleza.",
    opciones: [
      { texto: "Es una historia muy triste.", siguienteId: 64 },
      {texto: "¿Por qué decidió luchar contra los monstruos?",
        siguienteId: 65,
      },
    ],
  },
  {id: 63,texto:"Los aldeanos se quedaron conmocionados por su muerte. Muchos creyeron que había sido un héroe, otros lo consideraron un loco. Pero nadie sabe con certeza qué sucedió con él.",
    opciones: [
      { texto: "Qué misterioso...", siguienteId: 64 },
      { texto: "¿Crees que alguien le tendió una trampa?", siguienteId: 66 },
    ],
  },
  {id: 64,texto:"Así es, y lo peor de todo es que todo parece estar repitiéndose. Los monstruos siguen amenazando a la aldea, y nadie parece ser capaz de detenerlos.",
    opciones: [
      {texto: "¿Qué quieres decir con que se está repitiendo?",
        siguienteId: 67,
      },
      { texto: "¿No se sabe qué fue de él", siguienteId: 68 },
    ],
  },
  {id: 65,texto:"Dicen que su corazón estaba lleno de valor y justicia, y que no soportaba ver cómo los aldeanos sufrían a causa de los monstruos. Pero tal vez su causa era demasiado noble para este mundo.",
    opciones: [
      { texto: "Es una lástima que haya muerto.", siguienteId: 64 },
      {texto: "Su sacrificio no fue en vano si inspiró a otros a luchar.",
        siguienteId: 68,
      },
    ],
  },
  {id: 66,texto:"Es difícil decirlo. Hay quienes piensan que fue traicionado por alguien, pero otros creen que simplemente subestimó a las criaturas que habitaban el bosque.",
    opciones: [
      { texto: "Es un misterio que nunca se resolverá.", siguienteId: 64 },
      {texto: "Espero que no haya sido por culpa de la gente de esta aldea.",
        siguienteId: 68,
      },
    ],
  },
  {id: 67,texto:"Los héroes siempre acaban de la misma forma. Él siguió luchando por la libertad del pueblo, hasta que finalmente, desapareció sin dejar rastro...",
    opciones: [
      { texto: "¿Cómo desapareció?", siguienteId: 68 },
      { texto: "¿Alguien lo ha visto desde entonces?", siguienteId: 69 },
    ],
  },
  {id: 68,texto:"Nadie lo sabe a ciencia cierta. Algunos dicen que se adentró en la cueva de los monstruos y nunca regresó. Otros creen que fue capturado por los habitantes del castillo, y que su suerte fue sellada.",
    opciones: [
      { texto: "¿Cueva de los monstruos? ¿Qué es eso?", siguienteId: 70 },
      { texto: "¿Castillo? ¿Hay un castillo en la zona?", siguienteId: 71 },
    ],
  },
  {id: 69,texto:"No, nadie ha vuelto a verlo desde entonces. Algunos creen que murió en su intento de liberar al pueblo, otros piensan que simplemente se alejó, cansado de luchar sin éxito.",
    opciones: [
      { texto: "Qué triste... ¿Cómo pudo fallar?", siguienteId: 72 },
      {texto: "Supongo que no fue lo suficientemente fuerte.",
        siguienteId: 73,
      },
    ],
  },
  {id: 70,texto:"La cueva de los monstruos es un lugar peligroso, lleno de criaturas mortales. No es un lugar al que quieras ir a menos que tengas un buen motivo.",
    opciones: [
      { texto: "¿Cómo sabes todo esto?", siguienteId: 74 },
      { texto: "Gracias por la advertencia, no iré.", siguienteId: 75 },
    ],
  },
  {id: 71,texto:"Sí, hay un castillo en la zona, pero está bastante lejos de aquí. Es el hogar de la familia noble que gobierna estas tierras. Pero no te recomendaría que intentaras entrar allí sin una buena razón.",
    opciones: [
      { texto: "¿Qué tipo de razón sería esa?", siguienteId: 76 },
      { texto: "Lo tendré en cuenta, gracias.", siguienteId: 77 },
    ],
  },
  {id: 72,texto:"Nadie lo sabe con certeza. Tal vez subestimó el poder del enemigo, o no tenía los recursos necesarios para llevar a cabo su misión. Pero lo que está claro es que algo salió mal, y pagó un precio muy alto por ello.",
    final: true,
  },
  {id: 73,texto:"No estoy seguro de que sea justo decir eso. Tal vez simplemente se enfrentó a una fuerza abrumadora, o no tuvo la oportunidad de prepararse adecuadamente. No siempre es cuestión de fuerza bruta.",
    final: true,
  },
  {id: 74,texto:"Lo sé porque yo era uno de los que le seguían. Pero después de lo que pasó, aprendí que no se puede confiar en nadie. Ni siquiera en alguien que parece estar luchando por el bien común.",
    opciones: [
      { texto: "¿Qué sucedió?", siguienteId: 75 },
      { texto: "¿Por qué decidiste dejar de seguirlo?", siguienteId: 76 },
    ],
  },
  {id: 75,texto:"Fue hace muchos años. El viajero vino con grandes promesas de liberación y justicia, pero no tardamos en darnos cuenta de que era sólo un hombre más. Un hombre con sus propios intereses y motivaciones ocultas.",
    opciones: [
      { texto: "¿Qué pasó al final?", siguienteId: 77 },
      { texto: "¿Crees que podría volver a pasar?", siguienteId: 78 },
    ],
  },
  {id: 76,texto:"Me di cuenta de que no estaba haciendo nada bueno siguiendo a alguien sin siquiera conocer sus verdaderas intenciones. Desde entonces, he decidido ser más cuidadoso y evaluar bien en quién confío.",
    opciones: [
      { texto: "Es una buena forma de pensar.", siguienteId: 79 },
      {texto: "¿No te arrepientes de no haber luchado por la liberación?",
        siguienteId: 80,
      },
    ],
  },
  {id: 77,texto:"El viajero desapareció misteriosamente después de que su plan para liberar al pueblo fracasara. Muchos de los que le habían seguido acabaron malheridos o muertos. Fue un verdadero desastre.",
    opciones: [
      { texto: "Espero que algo así no vuelva a suceder.", siguienteId: 79 },
      { texto: "¿Crees que alguien más podría intentarlo?", siguienteId: 78 },
    ],
  },
  {id: 78,texto:"Todo se repite, ¿no crees? Siempre habrá alguien que quiera liberar al pueblo de su opresión. Alguien que prometa grandes cambios y que despierte la esperanza en los corazones de los más necesitados. Pero a veces, esa esperanza sólo trae dolor y tragedia.",
    final: true,
  },
  {id: 79,texto:"Creo que tenemos que ser cuidadosos, pero también estar dispuestos a luchar por lo que creemos justo. No podemos dejar que el miedo nos paralice.",
    final: true,
  },
  {id: 80,texto:"A veces me pregunto si hice lo correcto. Pero al final, creo que es mejor seguir viviendo y luchando por la libertad, aunque sea de forma más prudente y cauta.",
    final: true,
  },
];
